version: "3.8"
services:
  reverse-proxy:
    image: nginx:1.19.6-alpine
    container_name: reverse-proxy
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spcl40

  spcl40:
    image: spcl40
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: spcl40
    restart: always
