class Acc {
  heading: string;
  topics: string[];
  constructor(heading: string, topics: string[]) {
    this.heading = heading;
    this.topics = topics;
  }
}

type TableList = {
  term: number;
  tables: Acc[];
};

export const CurriculumDetails: TableList[] = [
  {
    term: 1,
    tables: [
      new Acc("Basics of Business", [
        "Understand how the business environment works",
        "Learn commonly used terms in business and related concepts",
        "Role of an accountant in the global business scenario",
      ]),
      new Acc("Basics of Accounting", [
        "Refresher on accounting processes and concepts",
        "Understanding the practical accounting terms and scenarios",
        "Learn to classify accounting transactions as Income / Expense / Asset / Liabilities",
      ]),
      new Acc("Preparation of Financial Statements", [
        "Learn How to prepare financial statements in Microsoft Excel",
        "Understand where each ledger is reported in the financial statements",
        "Learn how to prepare and read the Balance sheet",
        "Learn how to prepare and read the Profit and loss account",
        "Learn how to prepare and read the statements of Cash Flows",
      ]),
      new Acc("Accounting in ERP", [
        "Hands-on experience in accounting software",
        "Learn to prepare the books of accounts from scratch",
        "Identify the type of vouchers to be used in ERP for recording any transaction",
        "Generation of reports from ERP and analysis of information recorded in ERP",
        "Unleash the full potential of ERP using multiple reports and analytics",
        "Increasing your speed using shortcuts",
        "Learn features for statutory compliances in ERP",
      ]),
      new Acc("Introduction to Income Tax", [
        "Understanding the types of taxes in India",
        "Familiarize with the terms connected with Income tax",
        "How to access the government websites?",
        "How to compute taxes on income?",
        "How to be aware of your tax credits and tax demands?",
      ]),
      new Acc("Payment of Tax", [
        "How to pay tax at various points?",
        "Documents and returns related to Income tax",
        "Consequences related to non-compliance",
      ]),
      new Acc("TDS Return Filing", [
        "Learn to fill and file TDS Returns",
        "Familiarize with the common errors during TDS return filing",
        "Downloading required documents related to TDS compliance",
      ]),
      new Acc("Individual Taxation", [
        "Understand how salary and related components are taxed",
        "How to apply tax rates of income generated by individuals?",
        "Familiarize with TDS returns for salary",
      ]),
      new Acc("Concepts in GST", [
        "Familiarize with the terms connected with Goods and Service Tax (GST)",
        "When to register under GST?",
        "When to raise an invoice and learn the contents in a tax invoice",
        "How to understand type of GST levies and when to apply them?",
        "Learn about input tax credit and conditions for claiming them",
        "Understanding who should remit the GST to government",
        "Learn about real time documents generated through online",
      ]),
      new Acc("GST Returns", [
        "Practice preparation and filing of GST Returns",
        "Training to file GST returns using a multiple variety of transactions",
      ]),
      new Acc("Tools in Excel", [
        "Learn how to handle data in a spreadsheet",
        "Learn how to arrange your data into reportable formats",
        "Learn basic calculations and complex formulas",
        "Increase your speed using shortcuts",
        "Learn different reconciliations and summarizing using Microsoft Excel",
      ]),
    ],
  },
];
